package unidaq;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.FloatByReference;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.ShortByReference;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;

/**
 * JNA Wrapper for library <b>UniDaq</b><br>
 * This file was autogenerated by
 * <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit
 * <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> ,
 * <a href="http://rococoa.dev.java.net/">Rococoa</a>, or
 * <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class UniDaqLibrary implements Library {
	public static final String JNA_LIBRARY_NAME = "UniDaq";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(UniDaqLibrary.JNA_LIBRARY_NAME);
	static {
		Native.register(UniDaqLibrary.class, UniDaqLibrary.JNA_NATIVE_LIB);
	}
	public static final int IXUD_UNI_2V5 = (int) 16;
	public static final int Ixud_InvalidChannelNumber = (int) 14;
	public static final int PIOD56 = (int) 0x800140;
	public static final int Ixud_FIFOOverFlowErr = (int) 33;
	public static final int MAX_CFGCODE_NUMBER = (int) 24;
	public static final int PCI180x = (int) 0x345678;
	public static final int Ixud_ADCCTLTimeoutErr = (int) 20;
	public static final int IXUD_BI_0V5 = (int) 6;
	public static final int IXUD_BI_0V1 = (int) 10;
	public static final int Ixud_InvalidSetting = (int) 22;
	public static final int IXUD_HARDWARE_INT = (int) 1;
	public static final int IXUD_APC_READY_INT = (int) 2;
	public static final int Ixud_CfgCodeIndexErr = (int) 19;
	public static final int Ixud_FindCardIDErr = (int) 39;
	public static final int IXUD_UNI_5V = (int) 15;
	public static final int Ixud_AutoCreateEventErr = (int) 41;
	public static final int PISODA2 = (int) 0x800B00;
	public static final int Ixud_NoErr = (int) 0;
	public static final int ENABLEMEMIO = (int) 2;
	public static final int PISO813 = (int) 0x800A00;
	public static final int PEXC64 = (int) 0x800800;
	public static final int IXUD_AO_BI_10V = (int) 3;
	public static final int PCIM512 = (int) 0xDE9562;
	public static final int Ixud_CreateEventErr = (int) 29;
	public static final int ENABLEDMAAI = (int) 16;
	public static final int IXUD_UNI_0V001 = (int) 22;
	public static final int Ixud_RegThreadErr = (int) 42;
	public static final int PEXP32C32 = (int) 0x800820;
	public static final int PCIFC16 = (int) 0xB13017;
	public static final int PISOC64 = (int) 0x800800;
	public static final int Ixud_SetScanConfigErr = (int) 61;
	public static final int Ixud_RemoveIrqErr = (int) 26;
	public static final int IXUD_ANALOGTRIGGER_LEAVE = (int) 3;
	public static final int PIOD48 = (int) 0x800130;
	public static final int PEXP8R8 = (int) 0x1800FF;
	public static final int PCI100x = (int) 0x341002;
	public static final int Ixud_AllocateMemErr = (int) 23;
	public static final int Ixud_TimeOutErr = (int) 18;
	public static final int PEXDA = (int) 0x800400;
	public static final int PISOP32A32 = (int) 0x800870;
	public static final int IXUD_ANALOGTRIGGER_BELOW = (int) 2;
	public static final int Ixud_DIOModesErr = (int) 8;
	public static final int Ixud_CardIOErr = (int) 58;
	public static final int Ixud_BoardMappingErr = (int) 7;
	public static final int Ixud_DriverNoOpen = (int) 3;
	public static final int Ixud_InvalidValue = (int) 15;
	public static final int Ixud_SetBufInfoErr = (int) 38;
	public static final int PEXP64 = (int) 0x800810;
	public static final int PCI827 = (int) 0xDE3828;
	public static final int Ixud_CreateThreadErr = (int) 31;
	public static final int PCI826 = (int) 0xDE3827;
	public static final int Ixud_InvalidSize = (int) 10;
	public static final int PCI822 = (int) 0xDE3823;
	public static final int IXUD_AO_I_0_20_MA = (int) 16;
	public static final int IXUD_BI_1V25 = (int) 3;
	public static final int Ixud_GetSysBufferErr = (int) 28;
	public static final int PCITMC12 = (int) 0xDF2962;
	public static final int Ixud_InstallIrqErr = (int) 25;
	public static final int PIOD64 = (int) 0x800120;
	public static final int Ixud_ReleaseSpinLock = (int) 48;
	public static final int IXUD_UNI_1V25 = (int) 17;
	public static final int Ixud_SetMapAddressErr = (int) 52;
	public static final int Ixud_UnSupportedFun = (int) 13;
	public static final int MAX_BOARD_NUMBER = (int) 32;
	public static final int IXUD_AO_BI_20V = (int) 5;
	public static final int IXUD_ACTIVE_LOW = (int) 4;
	public static final int Ixud_InvalidOffset = (int) 54;
	public static final int IXUD_BI_0V3125 = (int) 5;
	public static final int Ixud_AcqireSpinLock = (int) 47;
	public static final int PEXD56 = (int) 0x800140;
	public static final int IXUD_BI_5V = (int) 1;
	public static final int IXUD_BI_20V = (int) 23;
	public static final int Ixud_FifoResetErr = (int) 44;
	public static final int Ixud_InvalidBlock = (int) 45;
	public static final int IXUD_BI_2V5 = (int) 2;
	public static final int Ixud_WriteEEPErr = (int) 57;
	public static final int PIOD96 = (int) 0x800110;
	public static final int PISOP8R8 = (int) 0x800830;
	public static final int Ixud_GetAIStatusTimeOut = (int) 17;
	public static final int IXUD_UNI_20V = (int) 13;
	public static final int PISO1730 = (int) 0x800820;
	public static final int Ixud_ReleaseMapAddressErr = (int) 53;
	public static final int IXUD_BI_0V001 = (int) 12;
	public static final int IXUD_AO_UNI_10V = (int) 2;
	public static final int Ixud_GetDriverVersionErr = (int) 4;
	public static final int PIOD168 = (int) 0x800150;
	public static final int PISO730A = (int) 0x800880;
	public static final int IXUD_BI_0V005 = (int) 8;
	public static final int Ixud_SetBufCountErr = (int) 37;
	public static final int PEXD48 = (int) 0x800130;
	public static final int IXUD_UNI_1V = (int) 19;
	public static final int PCI2602 = (int) 0x2CB656;
	public static final int Ixud_SetControlErr = (int) 49;
	public static final int MAX_AOCFGCODE_NUMBER = (int) 6;
	public static final int Ixud_GetMMIOMapStatus = (int) 62;
	public static final int Ixud_InvalidDataCount = (int) 56;
	public static final int PISO730 = (int) 0x800840;
	public static final int Ixud_ClearIntCountErr = (int) 27;
	public static final int Ixud_OpenDriverErr = (int) 1;
	public static final int PEXP16R16 = (int) 0x1800FF;
	public static final int PEXP16POR16 = (int) 0xD61E39;
	public static final int Ixud_GetBufStatus = (int) 36;
	public static final int Ixud_SetScanChannelErr = (int) 60;
	public static final int Ixud_GetIntInstStatus = (int) 35;
	public static final int PISOA64 = (int) 0x800850;
	public static final int Ixud_InstallEventErr = (int) 24;
	public static final int IXUD_ACTIVE_HIGH = (int) 8;
	public static final int PEX100x = (int) 0x341002;
	public static final int PCIP8R8 = (int) 0xD6102B;
	public static final int Ixud_InvalidPortNumber = (int) 11;
	public static final int Ixud_InvalidAddress = (int) 9;
	public static final int MAX_AO_CHANNEL = (int) 32;
	public static final int PISOP16R16U = (int) 0x1800FF;
	public static final int IXUD_UNI_0V1 = (int) 20;
	public static final int Ixud_ExceedBoardNumber = (int) 5;
	public static final int Ixud_InvalidAddr = (int) 46;
	public static final int MULTIPROCESSOR = (int) 1;
	public static final int PISO725 = (int) 0x8008FF;
	public static final int IXUD_BI_10V = (int) 0;
	public static final int MAX_EVENT_NUMBER = (int) 20;
	public static final int IXUD_ANALOGTRIGGER_ABOVE = (int) 1;
	public static final int PISOP32C32 = (int) 0x800820;
	public static final int PEX1202 = (int) 0x345672;
	public static final int IXUD_BI_0V05 = (int) 7;
	public static final int IXUD_UNI_10V = (int) 14;
	public static final int IXUD_UNI_0V01 = (int) 21;
	public static final int Ixud_EventThreadErr = (int) 40;
	public static final int IXUD_UNI_0V625 = (int) 18;
	public static final int IXUD_AO_UNI_5V = (int) 0;
	public static final int PCIP16R16 = (int) 0xD61E39;
	public static final int IXUD_AO_UNI_20V = (int) 4;
	public static final int Ixud_ShareHandleErr = (int) 55;
	public static final int IXUD_AO_BI_5V = (int) 1;
	public static final int PCID64 = (int) 0x2C90B8;
	public static final int Ixud_IOErr = (int) 59;
	public static final int Ixud_PnPDriverErr = (int) 2;
	public static final int IXUD_BI_0V625 = (int) 4;
	public static final int PIOD144 = (int) 0x800100;
	public static final int IXUD_ANALOGTRIGGER_ENTRY = (int) 4;
	public static final int Ixud_UnSupportedModel = (int) 12;
	public static final int Ixud_ThreadTimeOutErr = (int) 32;
	public static final int PISOP64 = (int) 0x800810;
	public static final int PEXP8POR8 = (int) 0xD6102B;
	public static final int PIO821 = (int) 0x800310;
	public static final int Ixud_FIFOTimeOutErr = (int) 34;
	public static final int Ixud_SearchCardErr = (int) 51;
	public static final int PCIM128 = (int) 0xDE9178;
	public static final int Ixud_SearchEventErr = (int) 43;
	public static final int PCIM256 = (int) 0xDE92A6;
	public static final int Ixud_InvalidChannels = (int) 50;
	public static final int IXUD_AO_I_4_20_MA = (int) 17;
	public static final int IXUD_BI_1V = (int) 9;
	public static final int Ixud_FindPCIIndexErr = (int) 21;
	public static final int Ixud_UnSupportedResolution = (int) 30;
	public static final int Ixud_FindBoardErr = (int) 6;
	public static final int Ixud_InvalidMode = (int) 16;
	public static final int PIODA = (int) 0x800400;
	public static final int IXUD_BI_0V01 = (int) 11;
	public static final int PCI1202 = (int) 0x345672;
	public static final int PCIM1024 = (int) 0xDEA074;
	public static final int PCI1602 = (int) 0x345676;

	/**
	 * Original signature : <code>WORD Ixud_GetDllVersion(DWORD*)</code><br>
	 * <i>native declaration : line 238</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetDllVersion(java.nio.IntBuffer)} and
	 *             {@link #Ixud_GetDllVersion(com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetDllVersion(IntByReference dwDLLVer);

	/**
	 * Original signature : <code>WORD Ixud_GetDllVersion(DWORD*)</code><br>
	 * <i>native declaration : line 238</i>
	 */
	public static native short Ixud_GetDllVersion(IntBuffer dwDLLVer);

	/**
	 * Driver functions<br>
	 * Original signature : <code>WORD Ixud_OptionMode(DWORD)</code><br>
	 * <i>native declaration : line 241</i>
	 */
	public static native short Ixud_OptionMode(int dwMode);

	/**
	 * Original signature : <code>WORD Ixud_DriverInit(WORD*)</code><br>
	 * <i>native declaration : line 242</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_DriverInit(java.nio.ShortBuffer)} and
	 *             {@link #Ixud_DriverInit(com.sun.jna.ptr.ShortByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_DriverInit(ShortByReference wTotalBoards);

	/**
	 * Original signature : <code>WORD Ixud_DriverInit(WORD*)</code><br>
	 * <i>native declaration : line 242</i>
	 */
	public static native short Ixud_DriverInit(ShortBuffer wTotalBoards);

	/**
	 * Original signature : <code>WORD Ixud_DriverClose()</code><br>
	 * <i>native declaration : line 243</i>
	 */
	public static native short Ixud_DriverClose();

	/**
	 * Original signature : <code>WORD Ixud_SearchCard(WORD*, DWORD)</code><br>
	 * <i>native declaration : line 244</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_SearchCard(java.nio.ShortBuffer, int)} and
	 *             {@link #Ixud_SearchCard(com.sun.jna.ptr.ShortByReference, int)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_SearchCard(ShortByReference wTotalBoards, int dwModelNo);

	/**
	 * Original signature : <code>WORD Ixud_SearchCard(WORD*, DWORD)</code><br>
	 * <i>native declaration : line 244</i>
	 */
	public static native short Ixud_SearchCard(ShortBuffer wTotalBoards, int dwModelNo);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetBoardNoByCardID(WORD*, DWORD, WORD)</code><br>
	 * <i>native declaration : line 245</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetBoardNoByCardID(java.nio.ShortBuffer, int, short)}
	 *             and
	 *             {@link #Ixud_GetBoardNoByCardID(com.sun.jna.ptr.ShortByReference, int, short)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetBoardNoByCardID(ShortByReference wBoardNo, int dwModelNumber, short wCardID);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetBoardNoByCardID(WORD*, DWORD, WORD)</code><br>
	 * <i>native declaration : line 245</i>
	 */
	public static native short Ixud_GetBoardNoByCardID(ShortBuffer wBoardNo, int dwModelNumber, short wCardID);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetCardInfo(WORD, PIXUD_DEVICE_INFO, PIXUD_CARD_INFO, char*)</code><br>
	 * <i>native declaration : line 246</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetCardInfo(short, unidaq.IXUD_DEVICE_INFO, unidaq.IXUD_CARD_INFO, java.nio.ByteBuffer)}
	 *             and
	 *             {@link #Ixud_GetCardInfo(short, unidaq.IXUD_DEVICE_INFO, unidaq.IXUD_CARD_INFO, com.sun.jna.Pointer)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetCardInfo(short wBoardNo, IXUD_DEVICE_INFO sDevInfo, IXUD_CARD_INFO sCardInfo,
			Pointer szModelName);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetCardInfo(WORD, PIXUD_DEVICE_INFO, PIXUD_CARD_INFO, char*)</code><br>
	 * <i>native declaration : line 246</i>
	 */
	public static native short Ixud_GetCardInfo(short wBoardNo, IXUD_DEVICE_INFO sDevInfo, IXUD_CARD_INFO sCardInfo,
			ByteBuffer szModelName);

	/**
	 * Original signature : <code>WORD Ixud_ReadPort(DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 248</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadPort(int, short, java.nio.IntBuffer)} and
	 *             {@link #Ixud_ReadPort(int, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadPort(int dwAddress, short wSize, IntByReference dwVal);

	/**
	 * Original signature : <code>WORD Ixud_ReadPort(DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 248</i>
	 */
	public static native short Ixud_ReadPort(int dwAddress, short wSize, IntBuffer dwVal);

	/**
	 * Original signature : <code>WORD Ixud_WritePort(DWORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 249</i>
	 */
	public static native short Ixud_WritePort(int dwAddress, short wSize, int dwVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadPort32(DWORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 250</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadPort32(int, java.nio.IntBuffer, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_ReadPort32(int, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadPort32(int dwAddress, IntByReference dwLow, IntByReference dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadPort32(DWORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 250</i>
	 */
	public static native short Ixud_ReadPort32(int dwAddress, IntBuffer dwLow, IntBuffer dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WritePort32(DWORD, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 251</i>
	 */
	public static native short Ixud_WritePort32(int dwAddress, int dwLow, int dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WritePhyMemory(DWORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 252</i>
	 */
	public static native short Ixud_WritePhyMemory(int dwAddress, short wSize, int dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadPhyMemory(DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 253</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadPhyMemory(int, short, java.nio.IntBuffer)} and
	 *             {@link #Ixud_ReadPhyMemory(int, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadPhyMemory(int dwAddress, short wSize, IntByReference dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadPhyMemory(DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 253</i>
	 */
	public static native short Ixud_ReadPhyMemory(int dwAddress, short wSize, IntBuffer dwValue);

	/**
	 * Digital I/O functions<br>
	 * Original signature : <code>WORD Ixud_SetDIOModes32(WORD, DWORD)</code><br>
	 * <i>native declaration : line 256</i>
	 */
	public static native short Ixud_SetDIOModes32(short wBoardNo, int dwDioMode);

	/**
	 * Original signature : <code>WORD Ixud_SetDIOMode(WORD, WORD, WORD)</code><br>
	 * <i>native declaration : line 257</i>
	 */
	public static native short Ixud_SetDIOMode(short wBoardNo, short wPortNo, short wDioMode);

	/**
	 * Original signature : <code>WORD Ixud_ReadDI(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 258</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadDI(short, short, java.nio.IntBuffer)} and
	 *             {@link #Ixud_ReadDI(short, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadDI(short wBoardNo, short wPortNo, IntByReference dwDIVal);

	/**
	 * Original signature : <code>WORD Ixud_ReadDI(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 258</i>
	 */
	public static native short Ixud_ReadDI(short wBoardNo, short wPortNo, IntBuffer dwDIVal);

	/**
	 * Original signature : <code>WORD Ixud_WriteDO(WORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 259</i>
	 */
	public static native short Ixud_WriteDO(short wBoardNo, short wPortNo, int dwDOVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadDI32(WORD, WORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 260</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadDI32(short, short, java.nio.IntBuffer, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_ReadDI32(short, short, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadDI32(short wBoardNo, short wPortN, IntByReference dwLow, IntByReference dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadDI32(WORD, WORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 260</i>
	 */
	public static native short Ixud_ReadDI32(short wBoardNo, short wPortN, IntBuffer dwLow, IntBuffer dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteDO32(WORD, WORD, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 261</i>
	 */
	public static native short Ixud_WriteDO32(short wBoardNo, short wPortNo, int dwLow, int dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadDIBit(WORD, WORD, WORD, WORD*)</code><br>
	 * <i>native declaration : line 262</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadDIBit(short, short, short, java.nio.ShortBuffer)}
	 *             and
	 *             {@link #Ixud_ReadDIBit(short, short, short, com.sun.jna.ptr.ShortByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadDIBit(short wBoardNo, short wPortNo, short wBitNo, ShortByReference wDIVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadDIBit(WORD, WORD, WORD, WORD*)</code><br>
	 * <i>native declaration : line 262</i>
	 */
	public static native short Ixud_ReadDIBit(short wBoardNo, short wPortNo, short wBitNo, ShortBuffer wDIVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteDOBit(WORD, WORD, WORD, WORD)</code><br>
	 * <i>native declaration : line 263</i>
	 */
	public static native short Ixud_WriteDOBit(short wBoardNo, short wPortNo, short wBitNo, short wDOVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_SoftwareReadbackDO(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 264</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_SoftwareReadbackDO(short, short, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_SoftwareReadbackDO(short, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_SoftwareReadbackDO(short wBoardNo, short wPortNo, IntByReference dwDOVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_SoftwareReadbackDO(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 264</i>
	 */
	public static native short Ixud_SoftwareReadbackDO(short wBoardNo, short wPortNo, IntBuffer dwDOVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_SetPWMOutput(WORD, WORD, WORD, float, float, float)</code><br>
	 * <i>native declaration : line 265</i>
	 */
	public static native short Ixud_SetPWMOutput(short wBoardNo, short wChannel, short wMode, float fFrequency,
			float fDutyRate, float fDelayUS);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartDO(WORD, WORD, DWORD, float, DWORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 266</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_StartDO(short, short, int, float, int, int, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_StartDO(short, short, int, float, int, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_StartDO(short wBoardNo, short wPortNo, int dwMode, float fSamplingRate,
			int dwDataCount, int dwCycleNum, IntByReference dwDOVal);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartDO(WORD, WORD, DWORD, float, DWORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 266</i>
	 */
	public static native short Ixud_StartDO(short wBoardNo, short wPortNo, int dwMode, float fSamplingRate,
			int dwDataCount, int dwCycleNum, IntBuffer dwDOVal);

	/**
	 * Original signature : <code>WORD Ixud_StopDO(WORD, WORD)</code><br>
	 * <i>native declaration : line 267</i>
	 */
	public static native short Ixud_StopDO(short wBoardNo, short wPortNo);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartDI(WORD, WORD, DWORD, float, DWORD)</code><br>
	 * <i>native declaration : line 268</i>
	 */
	public static native short Ixud_StartDI(short wBoardNo, short wPortNo, int dwMode, float fSamplingRate,
			int dwDataCount);

	/**
	 * Original signature : <code>WORD Ixud_StopDI(WORD, WORD)</code><br>
	 * <i>native declaration : line 269</i>
	 */
	public static native short Ixud_StopDI(short wBoardNo, short wPortNo);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetDIBufferH(WORD, WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 270</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetDIBufferH(short, short, int, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_GetDIBufferH(short, short, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetDIBufferH(short wBoardNo, short wPortNo, int dwDataCount, IntByReference hValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetDIBufferH(WORD, WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 270</i>
	 */
	public static native short Ixud_GetDIBufferH(short wBoardNo, short wPortNo, int dwDataCount, IntBuffer hValue);

	/**
	 * Callback functions<br>
	 * Original signature :
	 * <code>WORD Ixud_SetEventCallback(WORD, WORD, WORD, HANDLE*, PVOID, DWORD)</code><br>
	 * <i>native declaration : line 273</i>
	 */
	public static native short Ixud_SetEventCallback(short wBoardNo, short wEventType, short wInterruptSource,
			UniDaqLibrary.HANDLE hEvent, UniDaqLibrary.PVOID CallbackFun, int dwCallBackParameter);

	/**
	 * Original signature :
	 * <code>WORD Ixud_RemoveEventCallback(WORD, WORD)</code><br>
	 * <i>native declaration : line 274</i>
	 */
	public static native short Ixud_RemoveEventCallback(short wBoardNo, short wInterruptSource);

	/**
	 * Interrupt functions<br>
	 * Original signature : <code>WORD Ixud_InstallIrq(WORD, DWORD)</code><br>
	 * <i>native declaration : line 277</i>
	 */
	public static native short Ixud_InstallIrq(short wBoardNo, int dwInterruptMask);

	/**
	 * Original signature : <code>WORD Ixud_RemoveIrq(WORD)</code><br>
	 * <i>native declaration : line 278</i>
	 */
	public static native short Ixud_RemoveIrq(short wBoardNo);

	/**
	 * Timer/Counter functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadCounter(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 281</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadCounter(short, short, java.nio.IntBuffer)} and
	 *             {@link #Ixud_ReadCounter(short, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadCounter(short wBoardNo, short wChannel, IntByReference dwValue);

	/**
	 * Timer/Counter functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadCounter(WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 281</i>
	 */
	public static native short Ixud_ReadCounter(short wBoardNo, short wChannel, IntBuffer dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_SetCounter(WORD, WORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 282</i>
	 */
	public static native short Ixud_SetCounter(short wBoardNo, short wChannel, short wMode, int dwValue);

	/**
	 * Original signature : <code>WORD Ixud_DisableCounter(WORD, WORD)</code><br>
	 * <i>native declaration : line 283</i>
	 */
	public static native short Ixud_DisableCounter(short wBoardNo, short wChannel);

	/**
	 * Original signature :
	 * <code>WORD Ixud_SetFCChannelMode(WORD, WORD, WORD, WORD)</code><br>
	 * <i>native declaration : line 284</i>
	 */
	public static native short Ixud_SetFCChannelMode(short wBoardNo, short wChannel, short wMode, short wDelayMs);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadFrequency(WORD, WORD, float*, DWORD, WORD*)</code><br>
	 * <i>native declaration : line 285</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadFrequency(short, short, java.nio.FloatBuffer, int, java.nio.ShortBuffer)}
	 *             and
	 *             {@link #Ixud_ReadFrequency(short, short, com.sun.jna.ptr.FloatByReference, int, com.sun.jna.ptr.ShortByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadFrequency(short wBoardNo, short wChannel, FloatByReference fValue,
			int dwTimeOutMs, ShortByReference wStatus);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadFrequency(WORD, WORD, float*, DWORD, WORD*)</code><br>
	 * <i>native declaration : line 285</i>
	 */
	public static native short Ixud_ReadFrequency(short wBoardNo, short wChannel, FloatBuffer fValue, int dwTimeOutMs,
			ShortBuffer wStatus);

	/**
	 * Memory I/O functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadMemory(WORD, DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 288</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadMemory(short, int, short, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_ReadMemory(short, int, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadMemory(short wBoardNo, int dwOffsetByte, short wSize, IntByReference dwValue);

	/**
	 * Memory I/O functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadMemory(WORD, DWORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 288</i>
	 */
	public static native short Ixud_ReadMemory(short wBoardNo, int dwOffsetByte, short wSize, IntBuffer dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteMemory(WORD, DWORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 289</i>
	 */
	public static native short Ixud_WriteMemory(short wBoardNo, int dwOffsetByte, short wSize, int dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadMemory32(WORD, DWORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 290</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadMemory32(short, int, java.nio.IntBuffer, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_ReadMemory32(short, int, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadMemory32(short wBoardNo, int dwOffsetByte, IntByReference dwLow,
			IntByReference dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadMemory32(WORD, DWORD, DWORD*, DWORD*)</code><br>
	 * <i>native declaration : line 290</i>
	 */
	public static native short Ixud_ReadMemory32(short wBoardNo, int dwOffsetByte, IntBuffer dwLow, IntBuffer dwHigh);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteMemory32(WORD, DWORD, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 291</i>
	 */
	public static native short Ixud_WriteMemory32(short wBoardNo, int dwOffsetByte, int dwLow, int dwHigh);

	/**
	 * Analog Input functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadAI(WORD, WORD, WORD, float*)</code><br>
	 * <i>native declaration : line 294</i><br>
	 */
	public static native short Ixud_ReadAI(short wBoardNo, short wChannel, short wConfig, FloatByReference fValue);

	/**
	 * Analog Input functions<br>
	 * Original signature :
	 * <code>WORD Ixud_ReadAI(WORD, WORD, WORD, float*)</code><br>
	 * <i>native declaration : line 294</i>
	 */
	public static native short Ixud_ReadAI(short wBoardNo, short wChannel, short wConfig, FloatBuffer fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadAIH(WORD, WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 295</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_ReadAIH(short, short, short, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_ReadAIH(short, short, short, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_ReadAIH(short wBoardNo, short wChannel, short wConfig, IntByReference dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ReadAIH(WORD, WORD, WORD, DWORD*)</code><br>
	 * <i>native declaration : line 295</i>
	 */
	public static native short Ixud_ReadAIH(short wBoardNo, short wChannel, short wConfig, IntBuffer dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAI(WORD, WORD, WORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 296</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_PollingAI(short, short, short, int, java.nio.FloatBuffer)}
	 *             and
	 *             {@link #Ixud_PollingAI(short, short, short, int, com.sun.jna.ptr.FloatByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_PollingAI(short wBoardNo, short wChannel, short wConfig, int dwDataCount,
			FloatByReference fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAI(WORD, WORD, WORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 296</i>
	 */
	public static native short Ixud_PollingAI(short wBoardNo, short wChannel, short wConfig, int dwDataCount,
			FloatBuffer fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIH(WORD, WORD, WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 297</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_PollingAIH(short, short, short, int, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_PollingAIH(short, short, short, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_PollingAIH(short wBoardNo, short wChannel, short wConfig, int dwDataCount,
			IntByReference dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIH(WORD, WORD, WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 297</i>
	 */
	public static native short Ixud_PollingAIH(short wBoardNo, short wChannel, short wConfig, int dwDataCount,
			IntBuffer dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIScan(WORD, WORD, WORD[], WORD[], DWORD, float[])</code><br>
	 * <i>native declaration : line 298</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_PollingAIScan(short, short, java.nio.ShortBuffer, java.nio.ShortBuffer, int, java.nio.FloatBuffer)}
	 *             and
	 *             {@link #Ixud_PollingAIScan(short, short, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int, com.sun.jna.ptr.FloatByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_PollingAIScan(short wBoardNo, short wChannels, ShortByReference wChannelList,
			ShortByReference wConfigList, int dwDataCountPerChannel, FloatByReference fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIScan(WORD, WORD, WORD[], WORD[], DWORD, float[])</code><br>
	 * <i>native declaration : line 298</i>
	 */
	public static native short Ixud_PollingAIScan(short wBoardNo, short wChannels, ShortBuffer wChannelList,
			ShortBuffer wConfigList, int dwDataCountPerChannel, FloatBuffer fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIScanH(WORD, WORD, WORD[], WORD[], DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 299</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_PollingAIScanH(short, short, java.nio.ShortBuffer, java.nio.ShortBuffer, int, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_PollingAIScanH(short, short, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_PollingAIScanH(short wBoardNo, short wChannels, ShortByReference wChannelList,
			ShortByReference wConfigList, int dwDataCountPerChannel, IntByReference dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_PollingAIScanH(WORD, WORD, WORD[], WORD[], DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 299</i>
	 */
	public static native short Ixud_PollingAIScanH(short wBoardNo, short wChannels, ShortBuffer wChannelList,
			ShortBuffer wConfigList, int dwDataCountPerChannel, IntBuffer dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ConfigAI(WORD, WORD, DWORD, WORD, WORD)</code><br>
	 * <i>native declaration : line 300</i>
	 */
	public static native short Ixud_ConfigAI(short wBoardNo, short wFIFOSizeKB, int BufferSizeCount, short wCardType,
			short wDelaySettlingTime);

	/**
	 * Original signature :
	 * <code>WORD Ixud_ConfigAIEx(WORD, WORD, DWORD, WORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 301</i>
	 */
	public static native short Ixud_ConfigAIEx(short wBoardNo, short wFIFOSizeKB, int BufferSizeCount, short wCardType,
			short wDelaySettlingTime, int dwMode);

	/**
	 * Original signature : <code>WORD Ixud_ClearAIBuffer(WORD)</code><br>
	 * <i>native declaration : line 302</i>
	 */
	public static native short Ixud_ClearAIBuffer(short wBoardNo);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetBufferStatus(WORD, WORD*, DWORD*)</code><br>
	 * <i>native declaration : line 303</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetBufferStatus(short, java.nio.ShortBuffer, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_GetBufferStatus(short, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetBufferStatus(short wBoardNo, ShortByReference wBufferStatus,
			IntByReference dwDataCount);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetBufferStatus(WORD, WORD*, DWORD*)</code><br>
	 * <i>native declaration : line 303</i>
	 */
	public static native short Ixud_GetBufferStatus(short wBoardNo, ShortBuffer wBufferStatus, IntBuffer dwDataCount);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAI(WORD, WORD, WORD, float, DWORD)</code><br>
	 * <i>native declaration : line 304</i>
	 */
	public static native short Ixud_StartAI(short wBoardNo, short wChannel, short wConfig, float fSamplingRate,
			int dwDataCount);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartExtAI(WORD, WORD, WORD, WORD, float, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 305</i>
	 */
	public static native short Ixud_StartExtAI(short wBoardNo, short wActive, short wChannel, short wConfig,
			float fSamplingRate, int dwPostDataCount, int dwPreDataCount);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartExtAnalogTrigger(WORD, WORD, WORD, WORD, float, DWORD, DWORD, float, float)</code><br>
	 * <i>native declaration : line 306</i>
	 */
	public static native short Ixud_StartExtAnalogTrigger(short wBoardNo, short wActive, short wChannel, short wConfig,
			float fSamplingRate, int dwDataCount, int dwReserved, float fAboveTrgVoltage, float fBelowTrgVoltage);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartExtAIScan(WORD, WORD, WORD, WORD[], WORD[], float, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 307</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_StartExtAIScan(short, short, short, java.nio.ShortBuffer, java.nio.ShortBuffer, float, int, int)}
	 *             and
	 *             {@link #Ixud_StartExtAIScan(short, short, short, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, float, int, int)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_StartExtAIScan(short wBoardNo, short wChannels, short wActive,
			ShortByReference wChannelList, ShortByReference wConfigList, float fSamplingRate,
			int dwPostDataCountPerChannel, int dwPreDataCountPerChannel);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartExtAIScan(WORD, WORD, WORD, WORD[], WORD[], float, DWORD, DWORD)</code><br>
	 * <i>native declaration : line 307</i>
	 */
	public static native short Ixud_StartExtAIScan(short wBoardNo, short wChannels, short wActive,
			ShortBuffer wChannelList, ShortBuffer wConfigList, float fSamplingRate, int dwPostDataCountPerChannel,
			int dwPreDataCountPerChannel);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAIScan(WORD, WORD, WORD[], WORD[], float, DWORD)</code><br>
	 * <i>native declaration : line 308</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_StartAIScan(short, short, java.nio.ShortBuffer, java.nio.ShortBuffer, float, int)}
	 *             and
	 *             {@link #Ixud_StartAIScan(short, short, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, float, int)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_StartAIScan(short wBoardNo, short wChannels, ShortByReference wChannelList,
			ShortByReference wConfigList, float fSamplingRate, int dwDataCountPerChannel);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAIScan(WORD, WORD, WORD[], WORD[], float, DWORD)</code><br>
	 * <i>native declaration : line 308</i>
	 */
	public static native short Ixud_StartAIScan(short wBoardNo, short wChannels, ShortBuffer wChannelList,
			ShortBuffer wConfigList, float fSamplingRate, int dwDataCountPerChannel);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetAIBuffer(WORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 309</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetAIBuffer(short, int, java.nio.FloatBuffer)} and
	 *             {@link #Ixud_GetAIBuffer(short, int, com.sun.jna.ptr.FloatByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetAIBuffer(short wBoardNo, int dwDataCount, FloatByReference fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetAIBuffer(WORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 309</i>
	 */
	public static native short Ixud_GetAIBuffer(short wBoardNo, int dwDataCount, FloatBuffer fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetAIBufferH(WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 310</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_GetAIBufferH(short, int, java.nio.IntBuffer)} and
	 *             {@link #Ixud_GetAIBufferH(short, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_GetAIBufferH(short wBoardNo, int dwDataCount, IntByReference hValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_GetAIBufferH(WORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 310</i>
	 */
	public static native short Ixud_GetAIBufferH(short wBoardNo, int dwDataCount, IntBuffer hValue);

	/**
	 * Original signature : <code>WORD Ixud_StopAI(WORD)</code><br>
	 * <i>native declaration : line 311</i>
	 */
	public static native short Ixud_StopAI(short wBoardNo);

	/**
	 * Analog Output functions<br>
	 * Original signature : <code>WORD Ixud_ConfigAO(WORD, WORD, WORD)</code><br>
	 * <i>native declaration : line 314</i>
	 */
	public static native short Ixud_ConfigAO(short wBoardNo, short wChannel, short wCfgCode);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteAOVoltage(WORD, WORD, float)</code><br>
	 * <i>native declaration : line 315</i>
	 */
	public static native short Ixud_WriteAOVoltage(short wBoardNo, short wChannel, float fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteAOVoltageH(WORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 316</i>
	 */
	public static native short Ixud_WriteAOVoltageH(short wBoardNo, short wChannel, int hValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteAOCurrent(WORD, WORD, float)</code><br>
	 * <i>native declaration : line 317</i>
	 */
	public static native short Ixud_WriteAOCurrent(short wBoardNo, short wChannel, float fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_WriteAOCurrentH(WORD, WORD, DWORD)</code><br>
	 * <i>native declaration : line 318</i>
	 */
	public static native short Ixud_WriteAOCurrentH(short wBoardNo, short wChannel, int hValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAOVoltage(WORD, WORD, WORD, float, DWORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 319</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_StartAOVoltage(short, short, short, float, int, int, java.nio.FloatBuffer)}
	 *             and
	 *             {@link #Ixud_StartAOVoltage(short, short, short, float, int, int, com.sun.jna.ptr.FloatByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_StartAOVoltage(short wBoardNo, short wChannel, short wConfig, float fSamplingRate,
			int dwDataCount, int dwCycleNum, FloatByReference fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAOVoltage(WORD, WORD, WORD, float, DWORD, DWORD, float[])</code><br>
	 * <i>native declaration : line 319</i>
	 */
	public static native short Ixud_StartAOVoltage(short wBoardNo, short wChannel, short wConfig, float fSamplingRate,
			int dwDataCount, int dwCycleNum, FloatBuffer fValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAOVoltageH(WORD, WORD, WORD, float, DWORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 320</i><br>
	 * 
	 * @deprecated use the safer methods
	 *             {@link #Ixud_StartAOVoltageH(short, short, short, float, int, int, java.nio.IntBuffer)}
	 *             and
	 *             {@link #Ixud_StartAOVoltageH(short, short, short, float, int, int, com.sun.jna.ptr.IntByReference)}
	 *             instead
	 */
	@Deprecated
	public static native short Ixud_StartAOVoltageH(short wBoardNo, short wChannel, short wConfig, float fSamplingRate,
			int dwDataCount, int dwCycleNum, IntByReference dwValue);

	/**
	 * Original signature :
	 * <code>WORD Ixud_StartAOVoltageH(WORD, WORD, WORD, float, DWORD, DWORD, DWORD[])</code><br>
	 * <i>native declaration : line 320</i>
	 */
	public static native short Ixud_StartAOVoltageH(short wBoardNo, short wChannel, short wConfig, float fSamplingRate,
			int dwDataCount, int dwCycleNum, IntBuffer dwValue);

	/**
	 * Original signature : <code>WORD Ixud_StopAO(WORD, WORD)</code><br>
	 * <i>native declaration : line 321</i>
	 */
	public static native short Ixud_StopAO(short wBoardNo, short wChannel);

	public static class UCHAR extends PointerType {
		public UCHAR(Pointer address) {
			super(address);
		}

		public UCHAR() {
			super();
		}
	};

	public static class PVOID extends PointerType {
		public PVOID(Pointer address) {
			super(address);
		}

		public PVOID() {
			super();
		}
	};

	public static class HANDLE extends PointerType {
		public HANDLE(Pointer address) {
			super(address);
		}

		public HANDLE() {
			super();
		}
	};
}
